name: dacon
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy>=1.24.0
  - plotly
  - ipykernel
  - matplotlib
  - scikit-learn
  - nbformat
  - ipywidgets
  - tqdm
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu128
    - torch
    - torchvision
    - torchaudio
    - wandb